[project]
name = "tokysnatcher"
version = "0.3"
description = "A simple audiobook downloader for tokybook.com"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "gazpacho==1.1",
  "halo==0.0.31",
  "json5==0.9.28",
  "pick==2.4.0",
  "questionary==2.0.1",
  "requests==2.32.3",
  "tqdm==4.67.0",
  "urllib3==2.2.3",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rahaaatul/TokySnatcher"
"Bug Tracker" = "https://github.com/rahaaatul/TokySnatcher/issues"

[project.scripts]
tokysnatcher = 'tokysnatcher.__main__:main'
